# Generated by Django 2.2.17 on 2021-04-05 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_auto_20210405_0311'),
        ('authapp', '0004_auto_20210322_0328'),
    ]

    operations = [
    ]
