# Generated by Django 2.2.17 on 2021-04-05 00:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_merge_20210405_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 0, 31, 19, 540398, tzinfo=utc)),
        ),
    ]
